---
categories:
- ""
- ""
date: "2020-09-18"
draft: false
keywords: ""
slug: post_1
title: About me 
---

```{r, setup, include=FALSE}
knitr::opts_chunk$set(
  message = FALSE, 
  warning = FALSE, 
  tidy=FALSE,     # display code as typed
  size="small")   # slightly smaller font for code
options(digits = 3)

# default figure size
knitr::opts_chunk$set(
  fig.width=6.75, 
  fig.height=6.75,
  fig.align = "center"
)
```

##Background Info##

My name is *Stelios Tzavellos*, I was born and raised in Athens, Greece. Since a very young age I was always eager to explore the world and learn from different cultures, a mindset that has drove my decisions to study, work or visit different parts of the world. 

1. I completed my Bachelor’s degree in Civil Engineering at the University of Bath in the UK, obtaining a first-class honours

2. Having my mind set in civil engineering, I pushed myself outside of my comfort zone of Europe, and completed in 2015-16 a one-year work experience, as a site engineer for the metro construction project in Doha, Qatar

3. The summer following the completion of my Bachelor’s degree in 2017, I completed an internship at the project management department of Hilalco (Wade Adams group) in Dubai and Abu Dhabi working for a large infrastructure project

4. I completed a Master’s degree in Transport Engineering at Imperial College London, from which I graduated in 2019 with the Maurice Hanson Prize, first in my class

5. In December and January 2018-2019 I worked at L.E.K. Consulting in London as an external contractor on a due-dilligence engagement, an experience which in conjunction with my degree at Imperial College convinced me to pursue strategy consulting as a career path

6. In February 2019, I returned to Greece to complete my military service obligation until December 2019

7. Upon completion of my service, I prepared my application for London Business School and gained work experience from the field of investment banking in Greece

8. Being currently a student at LBS reading for the Masters in Analytics with Management program, an unparalleled passport built from knowledge, skills and connections, I am ready to kick-start my career in the highly competitive market of the consulting sector

##Interests and Activities##

Having worked hard to achieve my academic and professional goals, I have learned to value my free time and enrich my life with activities that develop my personality. Sports and especially football have been my passion since childhood, whilst during the summer months, Water-sports occupy a significant part of my free time, as I practice wake-boarding, windsurfing and scuba diving. I also adore traveling, which I consider to be a unique way to get out of your comfort zone, broaden your horizons, explore and experience life. Being lucky enough to have traveled to more than twenty countries across 5 continents, I have developed multicultural awareness, language skills and a distinct real-life education. Finally, I always aim to give back to society through volunteering activities. I have performed numerous environmental and social actions, however my most notable experience has been the one at the Kara Tepe refugee camp in Lesvos, Greece in 2016. I participated at a workshop organised by LATRA and UNHCR, where young designers and engineers from around the world spent a month hands-on redesigning, arranging and improving existing infrastructure of one of the largest refugee camps in Europe. 

My ambition is to never stop learning about promising technologies, the way different sectors and organisations operate and explore life as much as possible. 

